export const FETCH_BETS_REQUEST = 'FETCH_BETS_REQUEST'
export const FETCH_BETS_ERROR = 'FETCH_BETS_ERROR'
export const FETCH_BETS_SUCCESS = 'FETCH_BETS_SUCCESS'

export const SET_SLIP_BET = 'SET_SLIP_BET'
export const UNSET_SLIP_BET = 'UNSET_SLIP_BET'
export const CLEAR_SLIP_BETS = 'CLEAR_SLIP_BETS'

export const SET_STAKE = 'SET_STAKE'

export const POST_BETS_REQUEST = 'POST_BETS_REQUEST'
export const POST_BETS_ERROR = 'POST_BETS_ERROR'
export const POST_BETS_SUCCESS = 'POST_BETS_SUCCESS'

export const VIEW_AS_DECIMAL = 'VIEW_AS_DECIMAL'
export const VIEW_AS_FRACTIONAL = 'VIEW_AS_FRACTIONAL'
