export const FETCH_BETS_REQUEST = 'FETCH_BETS_REQUEST'
export const FETCH_BETS_ERROR = 'FETCH_BETS_ERROR'
export const FETCH_BETS_SUCCESS = 'FETCH_BETS_SUCCESS'

export const SET_ACTIVE_BET = 'SET_ACTIVE_BET'
export const UNSET_ACTIVE_BET = 'UNSET_ACTIVE_BET'
export const CLEAR_ACTIVE_BETS = 'CLEAR_ACTIVE_BETS'

export const ADD_BET_TO_SLIP = 'ADD_BET_TO_SLIP'
export const SET_STAKE = 'SET_STAKE'
export const REMOVE_BET_FROM_SLIP = 'REMOVE_BET_FROM_SLIP'
export const CLEAR_SLIP = 'CLEAR_SLIP'

export const POST_BETS_REQUEST = 'POST_BETS_REQUEST'
export const POST_BETS_ERROR = 'POST_BETS_ERROR'
export const POST_BETS_SUCCESS = 'POST_BETS_SUCCESS'
